name: bench

permissions: {}

env:
  RUSTFLAGS: "-C target-cpu=x86-64-v3 -C target-feature=+aes,+pclmulqdq"
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      filter:
        description: 'Optional filter for cargo bench (e.g., a specific benchmark name)'
        default: ''
        required: false
      ref:
        description: 'Optional git ref to benchmark'
        default: ''
        required: false

jobs:
  benchmarks:
    name: Benchmarks
    runs-on: "ubicloud-standard-4"
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Install stable
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772
        id: toolchain
        with:
          toolchain: stable

      - run: cargo --version

      - name: Install bencher
        uses: bencherdev/bencher@50fb1e138651a46d2fb704fab1adab38c181552e # v0.6.6

      - name: CPU information
        run: lscpu

      - name: Cache
        uses: ubicloud/rust-cache@65b3ff06b9bcc69d88c25e212f1ae3d14a0953c3

      - name: Run benchmarks
        env:
          BRANCH: ${{ github.ref_name }}
          FILTER: ${{ github.event.inputs.filter }}
          BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
        run: |
          bencher run \
          --project cryprot \
          --token "$BENCHER_API_TOKEN" \
          --branch "$BRANCH" \
          --testbed ubicloud-standard-4 \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-upper-boundary 0.99 \
          'cargo bench "$FILTER"'
